TIMEZONE="Asia/Taipei"

# Config
DOMSERVER_NAME="domjudge_domserver"
JUDGEHOST_NAME="domjudge_judgehost"
DATABASE_NAME="domjudge_database"

# Database config
MYSQL_ROOT_PASSWORD="@@CHANGE_ME@@"
MYSQL_USER="domjudge"
MYSQL_PASSWORD="@@CHANGE_ME@@"
MYSQL_DATABASE="domjudge"
MYSQL_DATA_PATH="/opt/domjudge/database_data"
MYSQL_MAX_CONNECTIONS="1000"
MYSQL_MAX_ALLOWED_PACKET="268435456"
MYSQL_INNODB_LOG_FILE_SIZE="268435456"

# Domserver config
FPM_MAX_CHILDREN="40"

# Judgehost config
DOMSERVER_BASEURL="http://${DOMSERVER_NAME}/"
JUDGE_HOST_COUNT="4"
JUDGEDAEMON_USERNAME="judgehost"
JUDGEDAEMON_PASSWORD="@@CHANGE_ME@@"

# Version Config
MARIADB_VERSION=10.8
DOMJUDGE_VERSION=7.3.4
