global:
  sendAnonymousUsage: false

log:
  level: INFO

accessLog: {}

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

providers:
  file:
    filename: /etc/traefik/config/domserver.yml

certificatesResolvers:
  letsEncrypt:
    acme:
      storage: /etc/traefik/acme/letsEncrypt.json
      httpChallenge:
        entryPoint: web
